# Generated by Django 6.0.1 on 2026-01-20 10:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('climate', '0001_initial'),
        ('hives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(default='Honey', max_length=100)),
                ('region', models.CharField(max_length=200)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('price_per_kg', models.FloatField(help_text='Price per kg in local currency')),
                ('seasonal_demand_factor', models.FloatField(help_text='Demand factor relative to annual average')),
                ('regional_supply_indicator', models.FloatField(help_text='Supply indicator (0-1)')),
            ],
        ),
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(default='Honey', max_length=100)),
                ('region', models.CharField(max_length=200)),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('forecast_date', models.DateField()),
                ('predicted_price_per_kg', models.FloatField(help_text='Predicted price per kg in local currency')),
                ('price_trend_forecast', models.FloatField(help_text='Price trend indicator (-1 to 1)')),
                ('hold_vs_sell_recommendation', models.CharField(choices=[('hold', 'Hold'), ('sell', 'Sell')], max_length=20)),
                ('best_market_timing', models.FloatField(help_text='Optimal timing score (0-1)')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('optimal_harvest_window_start', models.DateField()),
                ('optimal_harvest_window_end', models.DateField()),
                ('expected_production_volume', models.FloatField(help_text='Expected honey production in kg')),
                ('feeding_necessity_alert', models.BooleanField(default=False)),
                ('nectar_flow_probability', models.FloatField(help_text='Probability of good nectar flow (0-1)')),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hives.hive')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recommendation_type', models.CharField(choices=[('absconding_risk', 'Absconding Risk Mitigation'), ('nectar_flow', 'Nectar Flow Preparation'), ('harvest_timing', 'Harvest Timing'), ('feeding_schedule', 'Feeding Schedule'), ('market_timing', 'Market Timing')], max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1=highest priority, 5=lowest priority')),
                ('is_action_required', models.BooleanField(default=True)),
                ('climate_prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climate.climateprediction')),
                ('health_prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hives.colonyhealthprediction')),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hives.hive')),
                ('market_prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.priceprediction')),
                ('production_prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.productionprediction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
