# Generated by Django 6.0.1 on 2026-01-20 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('temperature_min', models.FloatField(help_text='Minimum temperature in Celsius')),
                ('temperature_max', models.FloatField(help_text='Maximum temperature in Celsius')),
                ('rainfall', models.FloatField(help_text='Rainfall in mm')),
                ('humidity_avg', models.FloatField(help_text='Average humidity percentage')),
                ('seasonal_trend', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClimatePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('forecast_date', models.DateField()),
                ('predicted_temperature_min', models.FloatField()),
                ('predicted_temperature_max', models.FloatField()),
                ('predicted_rainfall', models.FloatField()),
                ('predicted_humidity', models.FloatField()),
                ('nectar_flow_probability', models.FloatField(help_text='Probability of good nectar flow (0-1)')),
                ('heat_stress_index', models.FloatField(help_text='Heat stress indicator (0-1)')),
                ('moisture_stress_index', models.FloatField(help_text='Moisture stress indicator (0-1)')),
            ],
        ),
    ]
