# Generated by Django 6.0.1 on 2026-01-20 10:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('climate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hive_id', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('installation_date', models.DateField(default=django.utils.timezone.now)),
                ('bee_species', models.CharField(max_length=100)),
                ('queen_age_months', models.IntegerField()),
                ('colony_size_estimate', models.IntegerField(help_text='Estimated number of bees')),
            ],
        ),
        migrations.CreateModel(
            name='ColonyHealthPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('honey_yield_estimation', models.FloatField(help_text='Estimated honey yield in kg')),
                ('absconding_risk_score', models.FloatField(help_text='Risk of absconding (0-1)')),
                ('swarming_probability', models.FloatField(help_text='Probability of swarming (0-1)')),
                ('colony_stress_index', models.FloatField(help_text='Colony stress index (0-1)')),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('moderate', 'Moderate Concern'), ('critical', 'Critical')], default='healthy', max_length=50)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hives.hive')),
            ],
        ),
        migrations.CreateModel(
            name='HiveActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('weight_kg', models.FloatField(help_text='Hive weight in kg')),
                ('foraging_activity_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='1=low, 10=high')),
                ('aggressiveness_score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='1=calm, 10=aggressive')),
                ('brood_presence', models.BooleanField(default=False)),
                ('internal_temperature', models.FloatField(blank=True, help_text='Internal hive temperature in Celsius', null=True)),
                ('ambient_temperature', models.FloatField(blank=True, help_text='Ambient temperature in Celsius', null=True)),
                ('climate_prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climate.climateprediction')),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hives.hive')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
